import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import { Figtree } from "next/font/google";
import bg from '../public/hero-bg.jpg';
const inter = Inter({ subsets: ["latin"] });
const figtree = Figtree({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AIKoncipient - čtení smluv pomocí umělé inteligence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="antialiased">
        <header className="border-b border-b-gray-100 py-6 px-6 md:px-0">
          <div className="container mx-auto">
            <Link href="/">
              <Image
                src="./logo.svg"
                alt={"AIKoncipient logo"}
                width={160}
                height={30}
              />
            </Link>
          </div>
        </header>
        <main className={inter.className}>
          <div className="bg-cover bg-no-repeat bg-bottom" style={{backgroundImage: `url(${bg.src})`}}>
            <div className="container mx-auto flex flex-col space-y-6 py-10 md:py-20 px-6 md:px-0">
              <div className="space-y-5">
                <h1
                  className={[
                    "text-4xl md:text-5xl font-bold max-w-2xl leading-tight",
                    figtree.className,
                  ].join(" ")}
                >
                  Nechte si přečíst smlouvu během několika vteřin
                </h1>
                <p className="text-xl max-w-prose leading-normal">
                  Umím během několika vteřin přečíst smlouvu a navrhnout místa
                  na které se zaměřit. Neumím však dávat právní rady.
                </p>
              </div>
              <div>
                <Link
                  href="https://app.koncipient.info"
                  className={[
                    "text-xl font-semibold bg-black text-white py-4 px-10 rounded-md block text-center transition",
                    "hover:bg-purple-800",
                    "md:inline-block",
                    figtree.className,
                  ].join(" ")}
                >
                  Přečíst smlouvu
                </Link>
              </div>
              <div>
                <p className="opacity-50">
                  AI Koncipient je momentálně v{" "}
                  <span className="border border-gray-500 rounded inline-block px-2">
                    beta
                  </span>{" "}
                  verzi a testuje své schopnosti
                </p>
              </div>
            </div>
          </div>
          <div>
            <div className="container mx-auto">
              <h2>Rychlá analýza smluv</h2>
              <p>AI Koncipient během několika vteřin přečte až 10 stran A4</p>
              <p>
                AI Koncipient vytvoří srozumitelný přehled problémů na které
                během čtení narazil
              </p>
            </div>
          </div>
          <div>
            <div className="container mx-auto md:flex md:space-x-5">
              <div className="rounded-2xl border w-full shadow-xl p-8 space-y-4">
                <h2 className={["text-2xl font-semibold", figtree.className].join(' ')}>Individuální čtení</h2>
                <div>
                  <p className="border border-green-600 bg-green-50 py-1 px-2 inline-block rounded font-semibold text-green-700">20 Kč</p>
                </div>
                <ul className="list-inside list-disc">
                  <li>Až 4 000 znaků</li>
                  <li>Slabiny</li>
                  <li>Sumarizace</li>
                  <li>Návrhy úprav</li>
                </ul>
                <Link
                  href="https://app.koncipient.info"
                  className={[
                    "text-base font-semibold bg-black text-white py-2 px-5 rounded-md block text-center transition",
                    "hover:bg-purple-800",
                    "md:inline-block",
                    figtree.className,
                  ].join(" ")}
                >
                  Přečíst smlouvu
                </Link>
              </div>
              <div className="rounded-2xl border w-full shadow-xl p-8 space-y-4">
              <h2 className={["text-2xl font-semibold", figtree.className].join(' ')}>Advokátní kancelář</h2>
                <p className="border border-gray-600 bg-gray-50 py-1 px-2 inline-block rounded font-semibold text-gray-700">Individuální cena</p>
                <ul className="list-inside list-disc">
                  <li>Neomezené znaky</li>
                  <li>Analýza po odstavcích</li>
                  <li>Učení AI koncipienta</li>
                </ul>
                <Link
                  href="https://app.koncipient.info"
                  className={[
                    "text-base font-semibold bg-gray-200 text-black py-2 px-5 rounded-md block text-center transition",
                    "hover:bg-purple-800 hover:text-white",
                    "md:inline-block",
                    figtree.className,
                  ].join(" ")}
                >
                  Kontaktujte nás
                </Link>
              </div>
            </div>
          </div>
          <div>
            <div className="container mx-auto">
              <div>
                <h2>Příklad analýzy</h2>
                <p>
                  Vzorová smlouva o dílo, běžně dostupná na internetu. Do
                  smlouvy nebyly vloženy žádné konkrétní údaje.
                </p>
              </div>
              <div>
                <ul>
                  <li>
                    Nepřesně definovaný předmět smlouvy - specifikace Díla by
                    měla být uvedena v samotné smlouvě, nikoliv v příloze.
                  </li>
                  <li>
                    Nejasná formulace ohledně přenechání provádění Díla třetím
                    osobám - musí být jasně specifikováno, za jakých okolností a
                    pod jakými podmínkami může být Dílo přenecháno
                    subdodavatelům.
                  </li>
                  <li>
                    Neurčitý způsob určení ceny za Dílo - cena by měla být
                    specifikována konkrétně a podrobněji, než pouze jako odhad
                    nebo rozpočet.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </main>
        <footer>
          <div className="container mx-auto">&copy; 2023 koncipient.info</div>
        </footer>
      </div>
    </>
  );
}
