import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import { Inter } from "next/font/google";
import { Figtree } from "next/font/google";
import bg from "../public/hero-bg.jpg";
import {
  CheckCircle,
  CheckCircle2,
  Eye,
  FileText,
  Glasses,
  LayoutDashboard,
  Pilcrow,
} from "lucide-react";
const inter = Inter({ subsets: ["latin"] });
const figtree = Figtree({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AIKoncipient - čtení smluv pomocí umělé inteligence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-EHRPHCKZEG" />
      <Script
        src="https://cdn.volument.com/v1/volument-full.js"
        token="30248013af"
      />
      <Script id="ga" strategy="afterInteractive">
        {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-EHRPHCKZEG');
        `}
      </Script>
      <Script id="hotjar" strategy="afterInteractive">
        {`
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3416274,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    `}
      </Script>
      <div className="antialiased">
        <header className="border-b border-b-gray-100 py-6 px-6 md:px-0">
          <div className="container mx-auto">
            <Link href="/">
              <Image
                src="./logo.svg"
                alt={"AIKoncipient logo"}
                width={160}
                height={30}
              />
            </Link>
          </div>
        </header>
        <main className={inter.className}>
          <div className="container mx-auto px-4 md:px-0">
          VŠEOBECNÉ OBCHODNÍ PODMÍNKY pro e-shopy Tyto všeobecné obchodní
          podmínky (“Podmínky”) společnosti Tomáš Jeřábek, se sídlem Bulharská 1459, IČO 87976633, e-mail info@koncipient.info, adresa provozovny Bulharská 1459 Pardubice
          („My” nebo „Prodávající”) upravují v souladu s ustanovením § 1751
          odst. 1 zákona č. 89/2012 Sb., občanský zákoník, ve znění pozdějších
          předpisů („Občanský zákoník“) vzájemná práva a povinnosti Vás, jakožto
          kupujících, a Nás, jakožto prodávajících, vzniklá v souvislosti nebo
          na základě kupní smlouvy („Smlouva“) uzavřené prostřednictvím E-shopu
          na webových stránkách koncipient.info. Všechny informace o zpracování
          Vašich osobních údajů jsou obsaženy v Zásadách zpracování osobních
          údajů. Ustanovení těchto Podmínek
          jsou nedílnou součástí Smlouvy. Smlouva a Podmínky jsou vyhotoveny v
          českém jazyce. Znění Podmínek můžeme jednostranně měnit či doplňovat.
          Tímto ustanovením nejsou dotčena práva a povinnosti vzniklá po dobu
          účinnosti předchozího znění Podmínek. Jak jistě víte, tak komunikujeme
          primárně na dálku. Proto i pro naši Smlouvu platí, že jsou použity
          prostředky komunikace na dálku, které umožňují, abychom se spolu
          dohodli bez současné fyzické přítomnosti Nás a Vás, a Smlouva je tak
          uzavřena distančním způsobem v prostředí E-shopu, a to prostřednictvím
          rozhraní webové stránky („webové rozhraní E-shopu“). Pokud některá
          část Podmínek odporuje tomu, co jsme si společně schválili v rámci
          procesu Vašeho nákupu na Našem E-shopu, bude mít tato konkrétní dohoda
          před Podmínkami přednost. NĚKTERÉ DEFINICE Cena je finanční částka,
          kterou budete hradit za Zboží; Cena za dopravu je finanční částka,
          kterou budete hradit za doručení Zboží, a to včetně ceny za jeho
          zabalení; Celková cena je součet Ceny a Ceny za dopravu; DPH je daň
          z přidané hodnoty dle platných právních předpisů; Faktura je daňový
          doklad vystavený v souladu se zákonem o dani z přidané hodnoty na
          Celkovou cenu; Objednávka je Váš závazný návrh na uzavření Smlouvy o
          koupi Zboží s Námi; Uživatelský účet je účet zřízený na základě Vámi
          sdělených údajů, jež umožňuje uchování zadaných údajů a uchovávání
          historie objednaného Zboží a uzavřených Smluv; Vy jste osoba
          nakupující na Našem E-shopu, právními předpisy označovaná jako
          kupující; Zboží je vše, co můžete nakoupit na E-shopu. Obecná
          ustanovení a poučení Koupě Zboží je možná jen přes webové rozhraní
          E-shopu. Při nákupu Zboží je Vaše povinnost poskytnout Nám všechny
          informace správně a pravdivě. Informace, které jste Nám poskytli v
          Objednávce budeme tedy považovat za správné a pravdivé. Na našem
          E-shopu také poskytujeme přístup k hodnocení Zboží provedenému jinými
          spotřebiteli. Autenticitu takových recenzí zajišťujeme a kontrolujeme
          tím, že propojujeme hodnocení s konkrétními objednávkami, tudíž
          v interním systému u každého hodnocení vidíme i propojené ID
          objednávky, a tak jsme schopni ověřit a prokázat, že recenze pochází
          od reálného spotřebitele. UZAVŘENÍ SMLOUVY Smlouvu s Námi je možné
          uzavřít pouze v českém jazyce. Smlouva je uzavírána na dálku
          prostřednictvím E-shopu, přičemž náklady na použití komunikačních
          prostředků na dálku hradíte Vy. Tyto náklady se však nijak neliší od
          základní sazby, kterou hradíte za používání těchto prostředků (tedy
          zejména za přístup k internetu), žádné další náklady účtované Námi
          tedy nad rámec Celkové ceny nemusíte očekávat. Odesláním Objednávky
          souhlasíte s tím, že prostředky komunikace na dálku využíváme. K tomu,
          abychom mohli Smlouvu uzavřít, je třeba, abyste na E-shopu vytvořili
          Objednávku. V tomto návrhu musí být uvedeny následující údaje:
          Informace o nakupovaném Zboží (na E-shopu označujete Zboží, o jehož
          nákup máte zájem, tlačítkem „Přidat do košíku“); Informace o Ceně,
          Ceně za dopravu, způsobu platby Celkové ceny a požadovaném způsobu
          doručení Zboží; tyto informace budou zadány v rámci tvorby Objednávky
          v rámci uživatelského prostředí E-shopu, přičemž informace o Ceně,
          Ceně za dopravu a Celkové ceně budou uvedeny automaticky na základě
          Vámi zvolného Zboží, způsobu jeho doručení a platby; Své identifikační
          a kontaktní údaje sloužící k tomu, abychom mohli doručit Zboží,
          zejména tedy jméno, příjmení, doručovací adresu, telefonní číslo a
          e-mailovou adresu. V průběhu tvorby Objednávky může až do doby jejího
          dokončení údaje měnit a kontrolovat. Po provedení kontroly
          prostřednictvím stisku tlačítka „Objednat s povinností platby“
          Objednávku dokončíte. Před stiskem tlačítka musíte ale ještě potvrdit
          Vaše seznámení se a souhlas s těmito Podmínkami, v opačném případě
          nebude možné Objednávku dokončit. K potvrzení a souhlasu slouží
          zatrhávací políčko. Po stisku tlačítka „Objednat s povinností platby“
          budou všechny vyplněné informace odeslány přímo Nám. Vaši Objednávku
          Vám v co nejkratší době poté, kdy Nám bude doručena, potvrdíme zprávou
          odeslanou na Vaši e-mailovou adresu zadanou v Objednávce. Součástí
          potvrzení bude shrnutí Objednávky a tyto Podmínky formou přílohy
          e-mailové zprávy. Podmínky ve znění účinném ke dni Objednávky, tj. ve
          znění přiloženém jako příloha potvrzující e-mailové zprávy, tvoří
          nedílnou součást Smlouvy. Potvrzením Objednávky dochází k uzavření
          Smlouvy mezi Námi a Vámi. Mohou nastat i případy, kdy Vám nebudeme
          moci Objednávku potvrdit. Jedná se zejména o situace, kdy Zboží není
          dostupné nebo případy, kdy objednáte větší počet kusů Zboží, než kolik
          je z naší strany umožněno. Informaci o maximálním počtu Zboží Vám však
          vždy v rámci E-shopu předem poskytneme a neměla by pro Vás být tedy
          překvapivá. V případě, že nastane jakýkoli důvod, pro který nemůžeme
          Objednávku potvrdit, budeme Vás kontaktovat a zašleme Vám nabídku na
          uzavření Smlouvy v pozměněné podobě oproti Objednávce. Smlouva je
          v takovém případě uzavřena ve chvíli, kdy Naši nabídku potvrdíte.
          V případě, že v rámci E-shopu nebo v Objednávce bude uvedena zjevně
          chybná Cena, nejsme povinni Vám Zboží za tuto Cenu dodat ani
          v případě, kdy jste obdrželi potvrzení Objednávky, a tedy došlo
          k uzavření Smlouvy. V takové situaci Vás budeme bezodkladně
          kontaktovat a zašleme Vám nabídku na uzavření nové Smlouvy v pozměněné
          podobě oproti Objednávce. Nová Smlouva je v takovém případě uzavřena
          ve chvíli, kdy Naši nabídku potvrdíte. Za zjevnou chybu v Ceně se
          považuje například situace, kdy Cena neodpovídá obvyklé ceně u jiných
          prodejců nebo chybí či přebývá cifra. V případě, kdy dojde k uzavření
          Smlouvy, Vám vzniká závazek k zaplacení Celkové ceny. V případě, že
          máte zřízen Uživatelský účet, můžete učinit Objednávku jeho
          prostřednictvím. I v takovém případě máte ale povinnost zkontrolovat
          správnost, pravdivost a úplnost předvyplněných údajů. Způsob tvorby
          Objednávky je však totožný, jako v případě kupujícího bez
          Uživatelského účtu, výhodou však je, že není třeba opakovaně vyplňovat
          Vaše identifikační údaje. V některých případech umožňujeme na nákup
          Zboží využít slevu. Pro poskytnutí slevy je třeba, abyste v rámci
          návrhu Objednávky vyplnili údaje o této slevě do předem určeného pole.
          Pokud tak učiníte, bude Vám Zboží poskytnuto se slevou. Uživatelský
          účet Na základě Vaší registrace v rámci E-shopu můžete přistupovat do
          svého Uživatelského účtu. Při registraci Uživatelského účtu je Vaše
          povinnost uvést správně a pravdivě všechny zadávané údaje a v případě
          změny je aktualizovat. Přístup k Uživatelskému účtu je zabezpečen
          uživatelským jménem a heslem. Ohledně těchto přístupových je Vaší
          povinností zachovávat mlčenlivost a nikomu tyto údaje neposkytovat.
          V případě, že dojde k jejich zneužití, neneseme za to žádnou
          odpovědnost. Uživatelský účet je osobní, a nejste tedy oprávněni
          umožnit jeho využívání třetím osobám. Váš Uživatelský účet můžeme
          zrušit, a to zejména v případě, když jej více, než 12 měsíců
          nevyužíváte, či v případě, kdy porušíte své povinnosti dle Smlouvy.
          Uživatelský účet nemusí být dostupný nepřetržitě, a to zejména s
          ohledem na nutnou údržbu hardwarového a softwarového vybavení. CENOVÉ
          A PLATEBNÍ PODMÍNKY, VÝHRADA VLASTNICKÉHO PRÁVA Cena je vždy uvedena v
          rámci E-shopu, v návrhu Objednávky a samozřejmě ve Smlouvě. V případě
          rozporu mezi Cenou uvedenou u Zboží v rámci E-shopu a Cenou uvedenou
          v návrhu Objednávky se uplatní Cena uvedená v návrhu Objednávky, která
          bude vždy totožná s cenou ve Smlouvě. V rámci návrhu Objednávky je též
          uvedena Cena za dopravu, případně podmínky, kdy je doprava zdarma.
          Celková cena je uvedena včetně DPH včetně veškerých poplatků
          stanovených zákonem. Platbu Celkové ceny po Vás budeme požadovat po
          uzavření Smlouvy a před předáním Zboží. Úhradu Celkové ceny můžete
          provést následujícími způsoby: Bankovním převodem. Informace pro
          provedení platby Vám zašleme v rámci potvrzení Objednávky. V případě
          platby bankovním převodem je Celková cena splatná do 14 dnů
          Kartou online. V takovém případě probíhá platba přes platební bránu
          Stripe, přičemž platba se řídí podmínkami této platební
          brány, které jsou dostupné na adrese: stripe.com. V takovém případě dojde k platbě při doručení Zboží oproti
          předání Zboží. V případě platby dobírkou je Celková cena splatná při
          převzetí Zboží. Hotově při osobním odběru. Hotově lze hradit Zboží
          v případě převzetí v Naší provozovně. V případě platby hotově při
          osobním odběru je Celková cena splatná při převzetí Zboží. Faktura
          bude vystavena v elektronické podobě po uhrazení Celkové ceny a bude
          zaslána na Vaši e-mailovou adresu. Faktura bude též fyzicky přiložena
          ke Zboží a dostupná v Uživatelském úču. Vlastnické právo ke Zboží na
          Vás přechází až poté, co zaplatíte Celkovou cenu a Zboží převezmete.
          V případě platby bankovním převodem je Celková cena zaplacena
          připsáním na Náš účet, v ostatních případech je zaplacena v okamžik
          provedení platby. DORUČENÍ ZBOŽÍ, PŘECHOD NEBEZPEČÍ ŠKODY NA VĚCI
          Zboží Vám bude doručeno nejpozději do 14 dní dní způsobem dle
          Vaší volby, přičemž můžete vybírat z následujících možností: Osobní
          odběr na Naší provozovně uvedené v seznamu provozoven; Osobní odběr na
          výdejních místech společnosti Zásilkovna, Uloženka; Doručení
          prostřednictvím dopravních společností Česká pošta, PPL CZ, DHL,
          Zásilkovna; Zboží je možné doručit pouze v rámci České republiky. Doba
          doručení Zboží vždy závisí na jeho dostupnosti a na zvoleném způsobu
          doručení a platby. Předpokládaná doba doručení Zboží Vám bude sdělena
          v potvrzení Objednávky. Doba uvedená v těchto Podmínkách je pouze
          orientační a může se lišit od skutečné doby dodání. V případě osobního
          odběru na provozovně Vás vždy o možnosti vyzvednutí Zboží budeme
          informovat prostřednictvím e-mailu. Po převzetí Zboží od dopravce je
          Vaše povinnost zkontrolovat neporušenost obalu Zboží a v případě
          jakýchkoli závad tuto skutečnost neprodleně oznámit dopravci a Nám.
          V případě, že došlo k závadě na obalu, která svědčí o neoprávněné
          manipulaci a vstupu do zásilky, není Vaší povinností Zboží od dopravce
          převzít. V případě, kdy porušíte svoji povinnost převzít Zboží,
          s výjimkou případů dle čl. 6.4 Podmínek, nemá to za následek porušení
          Naší povinnosti Vám Zboží doručit. Zároveň to, že Zboží nepřevezmete,
          není odstoupení od Smlouvy mezi Námi a Vámi. Nám ale v takovém případě
          vzniká právo od Smlouvy odstoupit z důvodu Vašeho podstatného porušení
          Smlouvy, případně Zboží uskladnit, za což nám od Vás náleží úplata ve
          výši [BUDE DOPLNĚNO]. Pokud se rozhodneme odstoupit od Smlouvy, je
          odstoupení účinné v den, kdy Vám toto odstoupení doručíme. Odstoupení
          od Smlouvy nemá vliv na nárok na uhrazení Ceny za dopravu, případně na
          nárok na náhradu škody, pokud vznikla. Pokud je z důvodů vzniklých na
          Vaší straně Zboží doručováno opakovaně nebo jiným způsobem, než bylo
          ve Smlouvě dohodnuto, je Vaší povinností nahradit Nám náklady s tímto
          opakovaným doručením spojené. Platební údaje pro zaplacení těchto
          nákladů Vám zašleme na Vaši e-mailovou adresu uvedenou ve Smlouvě a
          jsou splatné 14 dnů od doručení e-mailu. Nebezpeční škody na Zboží na
          Vás přechází v okamžiku, kdy ho převezmete. V případě, kdy Zboží
          nepřevezmete, s výjimkou případů dle čl. 6.4 Podmínek, na Vás
          nebezpečí škody na Zboží přechází v okamžiku, kdy jste měli možnost ho
          převzít, ale z důvodů na Vaší straně k převzetí nedošlo. Přechod
          nebezpečí škody na Zboží pro Vás znamená, že od tohoto okamžiku nesete
          veškeré důsledky spojené se ztrátou, zničením, poškozením či jakýmkoli
          znehodnocením Zboží. V případě, že Zboží nebylo v E-shopu uvedeno jako
          skladem a byla uvedena orientační doba dostupnosti Vás budeme vždy
          informovat v případě: mimořádného výpadku výroby Zboží, přičemž Vám
          vždy sdělíme novou očekávanou dobu dostupnosti nebo informace o tom,
          že nebude možné Zboží dodat; prodlení s dodáním Zboží od Našeho
          dodavatele, přičemž Vám vždy sdělíme novou očekávanou dobu dodání.
          PRÁVA Z VADNÉHO PLNĚNÍ Zaručujeme, že v době přechodu nebezpečí škody
          na Zboží podle čl. 6.7 Podmínek je Zboží bez vad, zejména pak, že
          Zboží: odpovídá ujednanému popisu, druhu a množství, jakož i jakosti,
          funkčnosti, kompatibilitě, interoperabilitě a jiným ujednaným
          vlastnostem; je vhodné k účelu, pro který ho požadujete a s nímž
          souhlasíme; je dodáno s ujednaným příslušenstvím a pokyny k použití,
          včetně návodu k montáži nebo instalaci; je vhodné k účelu, k němuž se
          Zboží tohoto druhu obvykle používá; množstvím, jakostí a dalšími
          vlastnostmi, včetně životnosti, funkčnosti, kompatibility a
          bezpečnosti, odpovídá obvyklým vlastnostem Zboží téhož druhu, které
          můžete rozumně očekávat, i s ohledem na veřejná prohlášení učiněná
          námi nebo jinou osobou v témže smluvním řetězci, zejména reklamou nebo
          označením; je dodáno s příslušenstvím, včetně obalu, návodu k montáži
          a jiných pokynů k použití, které můžete rozumně očekávat; a odpovídá
          jakostí nebo provedením vzorku nebo předloze, které Vám byly
          poskytnuty před uzavřením smlouvy. Práva a povinnosti ohledně práv z
          vadného plnění se řídí příslušnými obecně závaznými právními předpisy
          (zejména ustanoveními § 2099 až 2117 a § 2161 až 2174b Občanského
          zákoníku a zákonem č. 634/1992 Sb., o ochraně spotřebitele, ve znění
          pozdějších předpisů). V případě, že bude mít Zboží vadu, tedy zejména
          pokud nebude splněna některá z podmínek dle čl. 7.1, můžete Nám
          takovou vadu oznámit a uplatnit práva z vadného plnění (tedy Zboží
          reklamovat) zasláním e-mailu či dopisu na Naše adresy uvedené u Našich
          identifikačních údajů, případně osobně na adrese [BUDE DOPLNĚNO]. Pro
          reklamaci můžete využít také vzorový formulář poskytovaný z Naší
          strany, který tvoří přílohu č. 1 Podmínek. V uplatnění práva z vadného
          plnění je třeba zvolit, jak chcete vadu vyřešit, přičemž tuto volbu
          nemůžete následně bez Našeho souhlasu změnit. Reklamaci vyřídíme
          v souladu s Vámi uplatněným právem z vadného plnění. Má-li Zboží vadu,
          máte následující práva: na odstranění vady dodáním nového Zboží bez
          vady, nebo dodáním chybějící části Zboží; nebo na odstranění vady
          opravou Zboží, ledaže by byl zvolený způsob odstranění vady nemožný
          nebo ve srovnání s druhým způsobem nepřiměřeně nákladný, což se
          posoudí zejména s ohledem na význam vady, hodnotu, kterou by Zboží
          mělo bez vady, a to, zda může být druhým způsobem vada odstraněna bez
          značných obtíží pro vás. Jsme oprávněni odmítnout vadu odstranit,
          je-li to nemožné nebo nepřiměřeně nákladné zejména s ohledem na význam
          vady a hodnotu, kterou by Zboží mělo bez vady. Dále máte právo na:
          přiměřenou slevu z Ceny; nebo odstoupení od Smlouvy, jestliže:
          odmítneme vadu odstranit nebo ji neodstraníme v souladu s právními
          předpisy; se vada projeví opakovaně, je vada podstatným porušením
          Smlouvy; nebo je z našeho prohlášení nebo z okolností zjevné, že vada
          nebude odstraněna v přiměřené době nebo bez značných obtíží pro Vás.
          Právo na odstoupení od Smlouvy nenáleží v případě, je-li vada Zboží
          nevýznamná. V případě, že jste si vadu na Zboží způsobili sami, práva
          z vadného plnění Vám nenáleží. Vadou Zboží není opotřebení Zboží
          způsobené jeho obvyklým užíváním nebo u použitého Zboží opotřebení
          odpovídající míře jeho předchozího používání. Při uplatnění reklamace
          Vám vystavíme písemné potvrzení, ve kterém bude uvedeno: datum, kdy
          jste reklamaci uplatnili; co je obsahem reklamace; jaký způsob
          vyřízení reklamace požadujete; Vaše kontaktní údaje pro účely
          poskytnutí informace o vyřízení reklamace. Nedohodneme-li se na delší
          lhůtě, do 30 dnů od obdržení reklamace odstraníme vady a poskytneme
          Vám informaci o vyřízení reklamace na uvedené kontaktní údaje. Pokud
          tato lhůta marně uplyne, můžete odstoupit od Smlouvy nebo požadovat
          přiměřenou slevu. O vyřízení reklamace Vás budeme informovat e-mailem
          a vydáme Vám potvrzení o datu a způsobu vyřízení reklamace. Pokud je
          reklamace oprávněná, náleží Vám náhrada účelně vynaložených nákladů.
          Tyto náklady jste povinni prokázat, např. účtenkami či potvrzeními o
          ceně za dopravu. V případě, že došlo k odstranění vady dodáním nového
          Zboží, je Vaší povinností Nám původní Zboží vrátit, náklady na toto
          vrácení však hradíme My. V případě, že jste podnikateli, je Vaší
          povinností oznámit a vytknout vadu bez zbytečného odkladu poté, co
          jste ji mohli zjistit, nejpozději však do tří dnů od převzetí Zboží.
          V případě, že jste spotřebitel, máte právo uplatit práva z vadného
          plnění u vady, která se vyskytne u spotřebního Zboží ve lhůtě 24
          měsíců od převzetí Zboží. odstoupení od smlouvy K odstoupení od
          Smlouvy, tedy k ukončení smluvního vztahu mezi Námi a Vámi od jeho
          počátku, může dojít z důvodů a způsoby uvedenými v tomto článku,
          případně v dalších ustanoveních Podmínek, ve kterých je možnost
          odstoupení výslovně uvedena. V případě, že jste spotřebitel, tedy
          osoba kupující Zboží mimo rámec své podnikatelské činnosti, máte
          v souladu s ustanovením §1829 občanského zákoníku právo odstoupit od
          Smlouvy bez udání důvodu ve lhůtě 14 dnů ode dne uzavření Smlouvy,
          resp. pokud se jedná o koupi zboží, pak do čtrnácti dnů od jeho
          převzetí. V případě, že jsme uzavřeli Smlouvu, jejímž předmětem je
          několik kusů Zboží nebo dodání několika částí Zboží, začíná tato lhůta
          běžet až dnem dodání posledního kusu nebo části Zboží, a v případě, že
          jsme uzavřeli Smlouvu, na základě které Vám budeme Zboží dodávat
          pravidelně a opakovaně, začíná běžet dnem dodání první dodávky. Od
          Smlouvy můžete odstoupit jakýmkoliv prokazatelným způsobem (zejména
          zasláním e-mailu nebo dopisu na Naše adresy uvedené u Našich
          identifikačních údajů). Pro odstoupení můžete využít také vzorový
          formulář poskytovaný z Naší strany, který tvoří přílohu č. 2 Podmínek.
          Ani jako spotřebitel však nemůžete od Smlouvy odstoupit v případech,
          kdy je předmětem Smlouvy plnění uvedené v § 1837 Občanského zákoníku.
          Lhůta k odstoupení dle čl. 8.2 Podmínek se považuje za zachovanou,
          pokud Nám v jejím průběhu odešlete oznámení, že od Smlouvy
          odstupujete. V případě odstoupení od Smlouvy dle čl. 8.2 Podmínek jste
          povinní Nám Zboží zaslat do 14 dnů od odstoupení a nesete náklady
          spojené s navrácením zboží k Nám. Vy máte naopak nárok na to, abychom
          Vám vrátili Cenu za dopravu, avšak pouze ve výši odpovídající
          nejlevnějšímu nabízenému způsobu dodání Zboží, který jsme pro dodání
          Zboží nabízeli. V případě odstoupení z důvodu, že My porušíme
          uzavřenou Smlouvu, hradíme i náklady spojené s navrácením zboží k Nám,
          ovšem opět pouze do výše Ceny za dopravu ve výši odpovídající
          nejlevnějšímu nabízenému způsobu dodání Zboží, který jsme při dodání
          Zboží nabízeli. V případě odstoupení od Smlouvy Vám bude Cena vrácena
          do 14 dnů ode dne účinnosti odstoupení na účet, ze kterého byla
          připsána, případně na účet zvolený odstoupení od Smlouvy. Částka však
          nebude vrácena dříve, než Zboží obdržíme, nebo Nám prokážete, že došlo
          k jeho zaslání zpět Nám. Zboží Nám prosím vracejte čisté, pokud možno
          včetně originálního obalu. V případě odstoupení od Smlouvy dle čl. 8.2
          Podmínek Nám však odpovídáte za snížení hodnoty Zboží, které vzniklo v
          důsledku nakládání s tímto zbožím jinak, než je nutné k tomu, abyste
          se seznámili s povahou, vlastnostmi a funkčností Zboží, tj. způsobem,
          jakým byste se se Zbožím seznamovali v kamenné prodejně. V případě, že
          jsme Vám ještě nevrátili Cenu, jsme oprávněni pohledávku z titulu
          nákladů započíst na Vaši pohledávku na vrácení Ceny. My jsme oprávněni
          odstoupit od Smlouvy kdykoliv před tím, než Vám dodáme Zboží, pokud
          existují objektivní důvody, proč není možné Zboží dodat (zejména
          důvody na straně třetích osob nebo důvody spočívající v povaze Zboží),
          a to i před uplynutím doby uvedené v čl. 6.1 Podmínek. Můžeme také od
          Smlouvy odstoupit, pokud je zjevné, že jste uvedli v Objednávce
          záměrně nesprávné informace. V případě, že nakupujete zboží v rámci
          své podnikatelské činnosti, tedy jako podnikatel, jsme oprávněni od
          Smlouvy odstoupit kdykoli, i bez udání důvodu. Řešení sporů se
          spotřebiteli Nejsme ve vztahu ke kupujícím vázáni žádnými kodexy
          chování ve smyslu ustanovení § 1826 odst. 1 písm. e) Občanského
          zákoníku. Vyřizování stížností spotřebitelů zajišťujeme
          prostřednictvím elektronické adresy info@koncipient.info. Informaci o
          vyřízení stížnosti zašleme na elektronickou adresu kupujícího. K
          mimosoudnímu řešení spotřebitelských sporů ze Smlouvy je příslušná
          Česká obchodní inspekce, se sídlem Štěpánská 567/15, 120 00 Praha 2,
          IČ: 000 20 869, internetová adresa: http://www.coi.cz. Platformu pro
          řešení sporů on-line nacházející se na internetové adrese
          http://ec.europa.eu/consumers/odr je možné využít při řešení sporů
          mezi prodávajícím a kupujícím, který je spotřebitelem, z kupní smlouvy
          uzavřené elektronickými prostředky. Evropské spotřebitelské centrum
          Česká republika, se sídlem Štěpánská 567/15, 120 00 Praha 2,
          internetová adresa: http://www.evropskyspotrebitel.cz je kontaktním
          místem podle Nařízení Evropského parlamentu a Rady (EU) č. 524/2013 ze
          dne 21. května 2013, o řešení spotřebitelských sporů on-line a o změně
          nařízení (ES) č. 2006/2004 a směrnice 2009/22/ES (nařízení o řešení
          spotřebitelských sporů on-line). Závěrečná ustanovení Pokud Náš a Váš
          právní vztah obsahuje mezinárodní prvek (tedy například budeme zasílat
          zboží mimo území České republiky), bude se vztah vždy řídit právem
          České republiky. Pokud jste však spotřebitelé, nejsou tímto ujednáním
          dotčena Vaše práva plynoucí z právních předpisů. Veškerou písemnou
          korespondenci si s Vámi budeme doručovat elektronickou poštou. Naše
          e-mailová adresa je uvedena u Našich identifikačních údajů. My budeme
          doručovat korespondenci na Vaši e-mailovou adresu uvedenou ve Smlouvě,
          v Uživatelském účtu nebo přes kterou jste nás kontaktovali. Smlouvu je
          možné měnit pouze na základě naší písemné dohody. My jsme však
          oprávněni změnit a doplnit tyto Podmínky, tato změna se však nedotkne
          již uzavřených Smluv, ale pouze Smluv, které budou uzavřeny po
          účinnosti této změny. O změně Vás však budeme informovat pouze
          v případě, že máte vytvořený Uživatelský účet (abyste tuto informaci
          měli v případě, že budete objednávat nové Zboží, změna však nezakládá
          právo výpovědi, jelikož nemáme uzavřenou Smlouvu, kterou by bylo možné
          vypovědět), nebo Vám na základě Smlouvy máme dodávat Zboží pravidelně
          a opakovaně. Informace o změně Vám zašleme na Vaši e-mailovou adresu
          nejméně 14 dní před účinností této změny. Pokud od Vás do 14 dnů od
          zaslání informace o změně neobdržíme výpověď uzavřené Smlouvy na
          pravidelné a opakované dodávky Zboží, stávají se nové podmínky
          součástí naší Smlouvy a uplatní se na další dodávku Zboží následující
          po účinnosti změny. Výpovědní doba v případě, že výpověď podáte, činí
          2 měsíce. V případě vyšší moci nebo událostí, které nelze předvídat
          (přírodní katastrofa, pandemie, provozní poruchy, výpadky
          subdodavatelů apod.), neneseme odpovědnost za škodu způsobenou
          v důsledku nebo souvislosti s případy vyšší moci, a pokud stav vyšší
          moci trvá po dobu delší než 10 dnů, máme My i Vy právo od Smlouvy
          odstoupit. Přílohou Podmínek je vzorový formulář pro reklamaci a
          vzorový formulář pro odstoupení od Smlouvy. Smlouva včetně Podmínek je
          archivována v elektronické podobě u Nás, ale není Vám přístupná. Vždy
          však tyto Podmínky a potvrzení Objednávky se shrnutím Objednávky
          obdržíte e-mailem a budete tedy mít vždy přístup ke Smlouvě i bez Naší
          součinnosti. Doporučujeme vždy potvrzení Objednávky a Podmínky uložit.
          Tyto Podmínky nabývají účinnosti 1.1.2023. Příloha č. 1 -
          Formulář pro reklamaci Adresát: info@koncipient.info. Uplatnění reklamace
          Zároveň žádám o vystavení potvrzení o uplatnění reklamace s uvedením,
          kdy jsem toto právo uplatnil, co je obsahem reklamace, jaký způsob
          vyřízení reklamace požaduji, spolu s uvedením mých kontaktních údajů
          pro účely poskytnutí informace o vyřízení reklamace. Datum:
          Podpis:Příloha č. 2 - Formulář pro odstoupení od Smlouvy Adresát:
          info@koncipient.info. Tímto prohlašuji, že odstupuji od Smlouvy: Je-li
          kupující spotřebitelem má právo v případě, že objednal zboží
          prostřednictvím e-shopu společnosti Tomáš Jeřábek („Společnost“)
          nebo jiného prostředku komunikace na dálku, mimo případy uvedené v §
          1837 zák. č. 89/2012 Sb., občanský zákoník, ve znění pozdějších
          předpisů odstoupit od již uzavřené kupní smlouvy do 14 dnů ode dne
          uzavření smlouvy, resp. pokud se jedná o koupi zboží, pak do čtrnácti
          dnů od jeho převzetí. V případě smlouvy, jejímž předmětem je několik
          kusů zboží nebo dodání několika částí zboží, začíná tato lhůta běžet
          až dnem dodání posledního kusu nebo části zboží, a v případě smlouvy,
          na základě které má být zboží dodáváno pravidelně a opakovaně, ode dne
          dodání první dodávky. Toto odstoupení oznámí kupující Společnosti
          písemně na adresu provozovny Společnosti nebo elektronicky na e-mail
          uvedený na vzorovém formuláři. Odstoupí-li kupující, který je
          spotřebitelem, od kupní smlouvy, zašle nebo předá Společnosti bez
          zbytečného odkladu, nejpozději do 14 dnů od odstoupení od kupní
          smlouvy, zboží, které od ní obdržel. Odstoupí-li kupující, který je
          spotřebitelem, od kupní smlouvy, vrátí mu Společnost bez zbytečného
          odkladu, nejpozději do 14 dnů od odstoupení od kupní smlouvy, všechny
          peněžní prostředky (kupní cenu dodaného zboží) včetně nákladů na
          dodání, které od něho na základě kupní smlouvy přijala, stejným
          způsobem. Jestliže kupující zvolil jiný, než nejlevnější způsob dodání
          zboží, který Společnost nabízí, vrátí Společnost kupujícímu náklady na
          dodání zboží pouze ve výši odpovídající nejlevnějšímu nabízenému
          způsobu dodání zboží. Společnost není povinna vrátit přijaté peněžní
          prostředky kupujícímu dříve, než zboží obdrží zpět nebo než kupující
          prokáže, že zboží Společnosti odeslal. Datum: Podpis:
          </div>
        </main>
        <footer className="bg-gray-900">
          <div className="container mx-auto">&copy; 2023 koncipient.info</div>
        </footer>
      </div>
    </>
  );
}
